# Generated by Django 6.0.4 on 2026-04-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_code_button',
            field=models.BooleanField(default=True, help_text="Show 'View Code' button that links to GitHub repository"),
        ),
    ]
