# Generated by Django 6.0.4 on 2026-04-29 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_show_code_button_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['priority', '-featured', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='portfolio_p_feature_b2909c_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Priority for ordering (1 = highest priority, higher numbers = lower priority)'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority', 'featured', 'status'], name='portfolio_p_priorit_286b82_idx'),
        ),
    ]
