# Generated by Django 6.0.4 on 2026-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_priority_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Priority for ordering (1 = highest priority, higher numbers = lower priority). Duplicates allowed.'),
        ),
    ]
